baseurl = "https://miradasiatica.github.io/mirada-asiatica/"
title = "Mirada Asiática"
languageCode = "es-es"
theme = "roadster"

[pagination]
  pagerSize = 10

[permalinks]
  [permalinks.term]
    tags = '/:slug/'

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Japón"
    url = "/categories/japon/"
    weight = 2
  [[menu.main]]
    name = "Corea"
    url = "/categories/corea/"
    weight = 3
  [[menu.main]]
    name = "China"
    url = "/categories/china/"
    weight = 4
  [[menu.main]]
    name = "Terror"
    url = "/categories/terror/"
    weight = 5
  [[menu.main]]
    name = "Clásicos"
    url = "/categories/clasicos/"
    weight = 6
  [[menu.main]]
    name = "Festivales"
    url = "/categories/festivales/"
    weight = 7

[Params]
  description = "Blog sobre cine asiático: reseñas, noticias y festivales"
  opengraph = true
  readmore = false
  authorbox = true
  pager = true
  post_meta = ["date", "categories"]
  mainSections = ["post"]

[Params.logo]
  subtitle = "Cine asiático: reseñas, noticias y festivales"

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5
  tags_counter = false
